# Generated by Django 5.2.6 on 2025-11-26 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=50, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('DeptID', models.ForeignKey(db_column='DeptID', null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'db_table': 'Project',
                'unique_together': {('ProjectID', 'ProjectName')},
            },
        ),
    ]
