# Generated by Django 5.2.6 on 2025-11-26 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=8, null=True)),
                ('HireDate', models.DateField(blank=True, null=True)),
                ('JobTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('Salary', models.CharField(blank=True, max_length=12, null=True)),
                ('DeptID', models.ForeignKey(db_column='DeptID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='departments.department')),
                ('ManagerID', models.ForeignKey(db_column='ManagerID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='employees.employee')),
            ],
            options={
                'db_table': 'Employee',
                'unique_together': {('EmpID', 'FirstName', 'LastName')},
            },
        ),
    ]
