# Generated by Django 5.2.6 on 2025-10-20 17:59

import django.db.models.deletion
import employees.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptID', models.AutoField(primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=30, null=True)),
                ('Location', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'Department',
                'unique_together': {('DeptID', 'DeptName')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=8, null=True)),
                ('HireDate', models.DateField(blank=True, null=True)),
                ('JobTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('Salary', models.CharField(blank=True, max_length=12, null=True)),
                ('ManagerID', models.ForeignKey(db_column='ManagerID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='employees.employee')),
                ('DeptID', models.ForeignKey(db_column='DeptID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employees.department')),
            ],
            options={
                'db_table': 'Employee',
                'unique_together': {('EmpID', 'FirstName', 'LastName')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=30, null=True)),
                ('DeptID', models.ForeignKey(db_column='DeptID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Locations', to='employees.department')),
            ],
            options={
                'db_table': 'DepartmentLocation',
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('PerformanceReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('ReviewDate', models.DateField(blank=True, null=True)),
                ('Rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True, max_length=500)),
                ('EmpID', models.ForeignKey(db_column='EmpID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employees.employee')),
                ('ManagerID', models.ForeignKey(db_column='ManagerID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviews', to='employees.employee')),
            ],
            options={
                'db_table': 'PerformanceReview',
                'unique_together': {('EmpID', 'PerformanceReviewID')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceReviewGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PerformanceGoals', models.CharField(blank=True, max_length=255, null=True)),
                ('PerformanceReviewID', models.ForeignKey(db_column='PerformanceReviewID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.performancereview')),
            ],
            options={
                'db_table': 'PerformanceReviewGoals',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=50, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('DeptID', models.ForeignKey(db_column='DeptID', null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.department')),
            ],
            options={
                'db_table': 'Project',
                'unique_together': {('ProjectID', 'ProjectName')},
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('TrainingID', models.AutoField(primary_key=True, serialize=False)),
                ('TrainingCourseName', models.CharField(max_length=30, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Training',
                'unique_together': {('TrainingID', 'TrainingCourseName')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('EmpID', models.OneToOneField(db_column='EmpID', default=employees.models.generate_employee_id, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attendance_records', serialize=False, to='employees.employee')),
                ('Date', models.DateField(blank=True, null=True)),
                ('TimeIn', models.CharField(blank=True, max_length=6, null=True)),
                ('TimeOut', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'Attendance',
                'unique_together': {('EmpID', 'Date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('EmpID', models.OneToOneField(db_column='EmpID', default='Temp-06e48105', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leave_requests', serialize=False, to='employees.employee')),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('LeaveType', models.CharField(blank=True, choices=[('sick', 'Sick'), ('vacation', 'Vacation'), ('other', 'Other')], max_length=10, null=True)),
                ('Status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True)),
            ],
            options={
                'db_table': 'LeaveRequest',
                'unique_together': {('EmpID', 'LeaveType', 'StartDate', 'EndDate')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('EmpID', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(blank=True, max_length=20, null=True)),
                ('HoursWorked', models.CharField(blank=True, max_length=10, null=True)),
                ('ProjectID', models.ForeignKey(db_column='ProjectID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_employees', to='employees.project')),
            ],
            options={
                'db_table': 'EmployeeProject',
                'unique_together': {('EmpID', 'ProjectID')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('EmpID', models.AutoField(primary_key=True, serialize=False)),
                ('CompletionStatus', models.CharField(blank=True, max_length=5, null=True)),
                ('TrainingID', models.ForeignKey(db_column='TrainingID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='employees.training')),
            ],
            options={
                'db_table': 'EmployeeTraining',
                'unique_together': {('EmpID', 'TrainingID')},
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('EmpID', models.OneToOneField(db_column='EmpID', default='Temp-9bca412e', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payrolls', serialize=False, to='employees.employee')),
                ('PayPeriodStart', models.DateField()),
                ('PayPeriodEnd', models.DateField()),
                ('HoursWorked', models.CharField(blank=True, max_length=10, null=True)),
                ('BaseSalary', models.FloatField(blank=True, null=True)),
                ('NetPay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('DeptID', models.ForeignKey(db_column='DeptID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
            ],
            options={
                'db_table': 'Payroll',
                'unique_together': {('EmpID', 'PayPeriodStart', 'PayPeriodEnd')},
            },
        ),
    ]
