# Generated by Django 5.2.6 on 2025-11-26 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('PerformanceReviewID', models.AutoField(primary_key=True, serialize=False)),
                ('ReviewDate', models.DateField(blank=True, null=True)),
                ('Rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Comments', models.TextField(blank=True, max_length=500)),
                ('EmpID', models.ForeignKey(db_column='EmpID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employees.employee')),
                ('ManagerID', models.ForeignKey(db_column='ManagerID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_reviews', to='employees.employee')),
            ],
            options={
                'db_table': 'PerformanceReview',
                'unique_together': {('EmpID', 'PerformanceReviewID')},
            },
        ),
        migrations.CreateModel(
            name='PerformanceReviewGoals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PerformanceGoals', models.CharField(blank=True, max_length=255, null=True)),
                ('PerformanceReviewID', models.ForeignKey(db_column='PerformanceReviewID', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance_review.performancereview')),
            ],
            options={
                'db_table': 'PerformanceReviewGoals',
            },
        ),
    ]
