# Generated by Django 5.2.6 on 2025-11-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereviewgoals',
            name='id',
        ),
        migrations.AddField(
            model_name='performancereviewgoals',
            name='GoalID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='performancereviewgoals',
            name='PerformanceGoals',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
