# Generated by Django 5.2.6 on 2025-11-26 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('EmpID', models.OneToOneField(db_column='EmpID', default='Temp-ad3f7f02', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leave_requests', serialize=False, to='employees.employee')),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('LeaveType', models.CharField(blank=True, choices=[('sick', 'Sick'), ('vacation', 'Vacation'), ('other', 'Other')], max_length=10, null=True)),
                ('Status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, null=True)),
            ],
            options={
                'db_table': 'LeaveRequest',
                'unique_together': {('EmpID', 'LeaveType', 'StartDate', 'EndDate')},
            },
        ),
    ]
