# Generated by Django 5.2.6 on 2025-11-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leave_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='EmpID',
            field=models.OneToOneField(db_column='EmpID', default='Temp-63c205ab', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leave_requests', serialize=False, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='LeaveType',
            field=models.CharField(blank=True, choices=[('Sick', 'Sick'), ('Vacation', 'Vacation'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='Status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='pending', max_length=20, null=True),
        ),
    ]
