# Generated by Django 5.2.6 on 2025-11-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('leave_request', '0002_alter_leaverequest_empid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='EmpID',
            field=models.OneToOneField(db_column='EmpID', default='Temp-d9cc085b', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='leave_requests', serialize=False, to='employees.employee'),
        ),
    ]
