# Generated by Django 5.2.6 on 2025-11-26 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('EmpID', models.OneToOneField(db_column='EmpID', default='Temp-fd418348', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payrolls', serialize=False, to='employees.employee')),
                ('PayPeriodStart', models.DateField()),
                ('PayPeriodEnd', models.DateField()),
                ('HoursWorked', models.CharField(blank=True, max_length=10, null=True)),
                ('BaseSalary', models.FloatField(blank=True, null=True)),
                ('NetPay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('DeptID', models.ForeignKey(db_column='DeptID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
            ],
            options={
                'db_table': 'Payroll',
                'unique_together': {('EmpID', 'PayPeriodStart', 'PayPeriodEnd')},
            },
        ),
    ]
