# Generated by Django 5.2.6 on 2025-11-26 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='EmpID',
            field=models.OneToOneField(db_column='EmpID', default='Temp-cfe0c559', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payrolls', serialize=False, to='employees.employee'),
        ),
    ]
