# Generated by Django 5.2.6 on 2025-11-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('payroll', '0002_alter_payroll_empid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='EmpID',
            field=models.OneToOneField(db_column='EmpID', default='Temp-f3dd5ca5', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='payrolls', serialize=False, to='employees.employee'),
        ),
    ]
