# Generated by Django 5.2.6 on 2025-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptID', models.AutoField(primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=30, null=True)),
                ('Location', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'Department',
                'unique_together': {('DeptID', 'DeptName')},
            },
        ),
    ]
