# Generated by Django 5.2.6 on 2025-11-26 16:59

import django.db.models.deletion
import emp_projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('EmpID', models.OneToOneField(db_column='EmpID', default=emp_projects.models.generate_employee_id, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_projects', serialize=False, to='employees.employee')),
                ('Role', models.CharField(blank=True, max_length=20, null=True)),
                ('HoursWorked', models.CharField(blank=True, max_length=10, null=True)),
                ('ProjectID', models.ForeignKey(db_column='ProjectID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_employees', to='projects.project')),
            ],
            options={
                'db_table': 'EmployeeProject',
                'unique_together': {('EmpID', 'ProjectID')},
            },
        ),
    ]
