# Generated by Django 5.2.6 on 2025-11-26 16:59

import django.db.models.deletion
import emp_training.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('EmpID', models.OneToOneField(db_column='EmpID', default=emp_training.models.generate_employee_id, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='employee_trainings', serialize=False, to='employees.employee')),
                ('CompletionStatus', models.CharField(blank=True, max_length=5, null=True)),
                ('TrainingID', models.ForeignKey(db_column='TrainingID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='training.training')),
            ],
            options={
                'db_table': 'EmployeeTraining',
                'unique_together': {('EmpID', 'TrainingID')},
            },
        ),
    ]
