# Generated by Django 5.2.6 on 2025-11-26 16:59

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('EmpID', models.OneToOneField(db_column='EmpID', default=attendance.models.generate_employee_id, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attendance_records', serialize=False, to='employees.employee')),
                ('Date', models.DateField(blank=True, null=True)),
                ('TimeIn', models.CharField(blank=True, max_length=6, null=True)),
                ('TimeOut', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'Attendance',
                'unique_together': {('EmpID', 'Date')},
            },
        ),
    ]
