# Generated by Django 5.2.6 on 2025-11-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('TrainingID', models.AutoField(primary_key=True, serialize=False)),
                ('TrainingCourseName', models.CharField(max_length=75, null=True)),
                ('Description', models.CharField(blank=True, max_length=150, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Training',
                'unique_together': {('TrainingID', 'TrainingCourseName')},
            },
        ),
    ]
